### ISSUE TITLE
AWS ElasticForwarder does not push logs when the Lambda closes due to a raised Exception

### ISSUE THREAD

**Issue by DanInacio** [elastic/elastic-serverless-forwarder#151]
Hi

We have an application hosted in AWS that receives JSON Requests and sends us a JSON Response with content we want to see in ElasticSearch. We started using AWS ElasticForwarder and came across a peculiar situation:

- When the request has the right format (and a response is sent), the ElasticForwarder is called and logs from CloudWatch are seen in ElasticSearch
BUT
- When the request is wrong (differently-named key, for example), raising an Exception, logs from CloudWatch show that an exception is raised and ElasticForwarder also throws an exception.

This results in having ElasticSearch only logging the requests that were correct, and all the errors become invisible from Elastic's point of view.
To reproduce, simply raise a KeyError Exception on the application that you want to track logs from.

Below you will find the AWS CloudWatch logs, from both our hosted application and the ElasticForwarder for a good and bad request.

----------------------------------------------------------
**Application Logs (Bad): Raises an Exception**
<img width="1319" alt="Screen Shot 2022-08-11 at 09 56 46" src="https://user-images.githubusercontent.com/16949504/184089059-085eb1d1-3030-4f1c-a205-2b5816b5fc47.png">

----------------------------------------------------------
**ElasticForwarder Logs (Bad): Abruptly stops running**
<img width="1317" alt="Screen Shot 2022-08-11 at 09 51 36" src="https://user-images.githubusercontent.com/16949504/184088816-257600e7-fad0-44a0-bfe9-e4ce15223592.png">

And the exception details:
```
{
    "@timestamp": "2022-08-11T07:37:12.607Z",
    "log.level": "error",
    "message": "exception raised",
    "ecs": {
        "version": "1.6.0"
    },
    "error": {
        "message": "string argument should contain only ASCII characters",
        "stack_trace": "  File \"/var/task/handlers/aws/utils.py\", line 84, in wrapper\n    return func(lambda_event, lambda_context)\n  File \"/var/task/handlers/aws/handler.py\", line 133, in lambda_handler\n    for (\n  File \"/var/task/handlers/aws/cloudwatch_logs_trigger.py\", line 105, in _handle_cloudwatch_logs_event\n    for log_event, json_object, ending_offset, starting_offset, newline_length in events:\n  File \"/var/task/storage/payload.py\", line 60, in get_by_lines\n    base64_decoded = base64.b64decode(self._payload, validate=True)\n  File \"/var/lang/lib/python3.9/base64.py\", line 80, in b64decode\n    s = _bytes_from_decode_data(s)\n  File \"/var/lang/lib/python3.9/base64.py\", line 39, in _bytes_from_decode_data\n    raise ValueError('string argument should contain only ASCII characters')\n",
        "type": "ValueError"
    },
    "log": {
        "logger": "root",
        "origin": {
            "file": {
                "line": 109,
                "name": "utils.py"
            },
            "function": "wrapper"
        },
        "original": "exception raised"
    },
    "process": {
        "name": "MainProcess",
        "pid": 9,
        "thread": {
            "id": 140534405121856,
            "name": "MainThread"
        }
    }
}
```
----------------------------------------------------------
**Application Logs (Good): Normal Execution**
<img width="1277" alt="Screen Shot 2022-08-11 at 09 57 47" src="https://user-images.githubusercontent.com/16949504/184095113-a6f5fa96-5634-48ed-a387-ca65e62c86ee.png">

----------------------------------------------------------
**ElasticForwarder Logs (Good): Normal Execution**
<img width="1236" alt="Screen Shot 2022-08-11 at 10 36 07" src="https://user-images.githubusercontent.com/16949504/184095480-7f0d2a23-137b-482d-8f79-14883533b1b2.png">

----------------------------------------------------------
**YAML Serverless App Repo Config File (removed data on the region, account, group naming and secrets...)**
```
inputs:
  - type: "cloudwatch-logs"
    id: "arn:aws:logs:[REGION]:[AWS_ACC_ID]:log-group:/aws/lambda/[LOG_GROUP_NAME]:*"
    outputs:
      - type: "elasticsearch"
        args:
          cloud_id: "arn:aws:secretsmanager:[REGION]:[AWS_ACC_ID]:secret:[SECRET_NAME]:[SECRET_KEY]"
          username: "arn:aws:secretsmanager:[REGION]:[AWS_ACC_ID]:secret:[SECRET_NAME]:[SECRET_KEY]"
          password: "arn:aws:secretsmanager:[REGION]:[AWS_ACC_ID]:secret:[SECRET_NAME]:[SECRET_KEY]"
          es_datastream_name: "logs-generic-default"
          batch_max_actions: 500
          batch_max_bytes: 10485760
```
