### ISSUE TITLE
ESF: Support for AWS Secrets manager expansion in config yaml

### ISSUE THREAD

**Issue by aspacca** [elastic/elastic-serverless-forwarder#19]
1.  `share.config.parse_config` should be refactored to receive a list of expanders callable:

```
def parse_config(config_yaml: str, expanders: list[Callable[[str], str]] = []) -> Config:
    for expander in expanders:
        config_yaml = expander(config_yaml)
```

2. Implements an expander for AWS secrets manager (somewhere in `share.config.aws_sm_expander`, up to you):
- Look for entries in the format `arn:aws:secretsmanager:AWS_REGION:AWS_ACCOUNT_ID:secret:SECRET_NAME:JSON_SECRET_KEY` and replace with the value of the fetched secret for the given json secret key
- Beware that the ARN of a secret is `arn:aws:secretsmanager:AWS_REGION:AWS_ACCOUNT_ID:secret:SECRET_NAME`, the secret will be in json format so we have to reference also the key appending `:JSON_SECRET_KEY` in the reference in the config file.
- If multiple json keys for the same secret ARN are referenced we should fetch the secret only once.
- The expander will take as input a str with the config yaml and return as output the same config yaml with the secrets expansion applied

3. Add unit test coverage for happy, sad and bad paths

4. Add the expander in the aws handler (`handlers/aws/handler.py:37`)

5. Change the integration test `tests.handlers.aws.test_handler.TestLambdaHandlerSuccess.test_lambda_handler` to have at least one secret in the config file

6. Document the feature in `docs/README_AWS.md`

feel free to split further the ticket in multiple ones for every steps

**Comment by aspacca** [comment]
sample config:
```
inputs:
  - type: "sqs"
    id: "arn:aws:sqs:eu-central-1:123456789:a_queue"
    outputs:
      - type: "elasticsearch"
        args:
          cloud_id: "cloud_id:bG9jYWxob3N0OjkyMDAkMA=="
          api_key: ""arn:aws:secretsmanager:eu-central-1:123456789:secret:a_secret_in_secretsmanager:a_json_key_in_the_secret""
          dataset: "generic"
          namespace: "default"
```

any value in the yaml can be an AWS Secrets Manager ARN (plus the `:JSON_SECRET_KEY`)
