### ISSUE TITLE
ESF: Custom tag support

### ISSUE THREAD

**Issue by aspacca** [elastic/elastic-serverless-forwarder#23]
1. config structure should accept a `tags` param as string list for output type `elasticsearch` (https://github.com/elastic/elastic-serverless-forwarder/blob/main/docs/README-AWS.md#s3_config_file)
```
inputs:
  - type: "sqs"
    id: "arn:aws:sqs:%REGION%:%ACCOUNT%:%QUEUENAME%"
    outputs:
      - type: "elasticsearch"
        args:
          # either elasticsearch_url or cloud_id, elasticsearch_url takes precedence
          elasticsearch_url: "http(s)://domain.tld:port"
          cloud_id: "cloud_id:bG9jYWxob3N0OjkyMDAkMA=="
          # either api_key or username/password, apy_key takes precedence
          api_key: "YXBpX2tleV9pZDphcGlfa2V5X3NlY3JldAo="
          username: "username"
          password: "password"
          dataset: "generic"
          namespace: "default"
          tags:
            - tag1
            - tag2
            - tag3
```

2. `share.config.ElasticSearchOutput` should accept an extra `__init__` params for `tags` values coming from config
3. `shippers.es.ElasticsearchShipper` should accept an extra `__init__` params for `tags` values coming from config
4. `shippers.factory.ShipperFactory.create_from_output` should be adapted to pass `tags` for elasticsearch output type
5. `shippers.es.ElasticsearchShipper._enrich_event` should merge `tags` key for `event_payload` with the tags coming from input
6. Add unit test coverage for happy, sad and bad paths

7. Change the integration test `tests.handlers.aws.test_handler.TestLambdaHandlerSuccess.test_lambda_handler` to have at least one tags in the config file

8. Document the feature in `docs/README_AWS.md`

feel free to split further the ticket in multiple ones for every steps
