### ISSUE TITLE
deploying more than one instance of the elastic-serverless-forwarder fails with The following resource(s) failed to create: [ElasticServerlessForwarderEventMacro].

### ISSUE THREAD

**Issue by russelw-procore** [elastic/elastic-serverless-forwarder#265]
Deployed elastic-serverless-forwarder according to the docs from SAR using the AWS Console.
Attempted to deploy a second instance for a different environment/cluster config and got a failure with automatic rollback.  Tried several more times, always failed.  Used SAM cli to deploy with the --disable-rollback flag set and was able to determine that the Macro function name defined by the second instance is colliding with the first instance.
![Screenshot 2023-03-01 at 2 25 43 PM](https://user-images.githubusercontent.com/46798245/222269477-1f0e7e0c-4747-41eb-b42b-cb6f4d9fd9ec.png)

Screenshot attached showing the console complaining about the macro function collision.  

CFN template snippet used to deploy SAR app here:

```
  Transform: AWS::Serverless-2016-10-31
  Resources:
    elasticserverlessforwarder:
      Type: AWS::Serverless::Application
      Properties:
        Location:
          ApplicationId: arn:aws:serverlessrepo:eu-central-1:267093732750:applications/elastic-serverless-forwarder
          SemanticVersion: '1.7.1'
        Parameters: 
 ```
