### ISSUE TITLE
Support wildcard ids for cloudwatch logs input

### ISSUE THREAD

**Issue by dchocoboo** [elastic/elastic-serverless-forwarder#334]
Currently in the inputs i specify in the block
```
- type: "cloudwatch-logs"
    id: "arn:aws:logs:ap-southeast-1:awsaccountid:log-group:myloggroup:*"
    outputs:
      - type: "elasticsearch"
        args:
          cloud_id: "${elastic_cloud_id}"
          api_key: "${elastic_api_key}"
          es_datastream_name: "logs-generic-default"
          batch_max_actions: 500 # optional: default value is 500
          batch_max_bytes: 10485760 # optional: default value is 10485760
```

would be nice if the log group can also use wildcard? instead of just log stream.
```
arn:aws:logs:ap-southeast-1:awsaccountid:log-group:application1-log-*:*
arn:aws:logs:ap-southeast-1:awsaccountid:log-group:application2-log-*:*
```

currently i have massive amounts of log groups to be ingested, while their outputs are identical.
its really redundant to loop every single one of them
