### ISSUE TITLE
Support SSM (Systems Manager) parameters

### ISSUE THREAD

**Issue by ltflb-bgdi** [elastic/elastic-serverless-forwarder#728]
**Describe the enhancement:**
There are two ways to store secrets in AWS:
- [AWS Secrets-Manager](https://aws.amazon.com/de/secrets-manager/)
- [SSM parameter store](https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-parameter-store.html)

Currently, only aws secrets are supported:
[config.yaml](https://www.elastic.co/guide/en/esf/current/aws-elastic-serverless-forwarder-configuration.html#use-secrets-manager)
[Deployment](https://www.elastic.co/guide/en/esf/current/aws-deploy-elastic-serverless-forwarder.html#_general_configuration)

Even though the docu only mentions secrets manager, the name of the parameter  `ElasticServerlessForwarderSSMSecrets` gives the impression that SSM is suppored as well, what seems not to be the case.

It would be very helpful to additionally support ssm parameters as well.

**Describe a specific use case for the enhancement or feature:**
Using credentials stored in ssm parameter store instead of sectets manager

**Config example/proposal**

Deployment:
```
parameter:
  ElasticServerlessForwarderSSMParameters: ["arn:aws:ssm:eu-central-1:123456:parameter/es_url"]
  ```
config.yaml:
```
inputs:
  - type: "s3-sqs"
    id: "arn:aws:sqs:%REGION%:%ACCOUNT%:%QUEUENAME%"
    outputs:
      - type: "elasticsearch"
        args:
          elasticsearch_url: "arn:aws:ssm:eu-central-1:123456789:parameter:es_url"
```
