### ISSUE TITLE
Deployment method using AWS Console doesn't work

### ISSUE THREAD

**Issue by tetianakravchenko** [elastic/elastic-serverless-forwarder#732]
I followed documentation - https://www.elastic.co/guide/en/esf/current/aws-deploy-elastic-serverless-forwarder.html#aws-serverless-forwarder-deploy-console

during installation - I've set only `ElasticServerlessForwarderS3ConfigFile` in format `s3://<config-bucket-name>/config.yaml`
```
inputs:
  - type: "cloudwatch-logs"
    id: "arn:aws:logs:...:...:log-group:/aws/lambda/name-test:*"

    outputs:
      - type: "elasticsearch"
        args:
          # either elasticsearch_url or cloud_id, elasticsearch_url takes precedence if both are included
          elasticsearch_url: "https://..."
          # cloud_id: "cloud_id:..."
          # either api_key or username/password, username/password takes precedence if both are included
          # api_key: "..."
          username: "..."
          password: "..."
          es_datastream_name: "logs-generic-default"
```

and installation is failing:
<img width="2451" alt="Screenshot 2024-07-01 at 15 35 26" src="https://github.com/elastic/elastic-serverless-forwarder/assets/28299531/4d06015a-3620-42d3-8aa6-921e1f886a3f">

View stack event:
<img width="1861" alt="Screenshot 2024-07-01 at 15 57 33" src="https://github.com/elastic/elastic-serverless-forwarder/assets/28299531/7e0b46f0-142b-4c4f-a0e4-86e7b314b9c4">

cc @constanca-m

**Comment by constanca-m** [comment]
I have tried to deploy it. I updated the needed variables:

- The cloudwatch logs group here:
![image](https://github.com/elastic/elastic-serverless-forwarder/assets/113898685/c522c2ae-f32e-43ff-8db8-98289d22b7a4)
In my case, the value is `arn:aws:logs:eu-north-1:627286350134:log-group:constanca-test-esf:*`

- And the S3 bucket to the config file:
![image](https://github.com/elastic/elastic-serverless-forwarder/assets/113898685/2707422a-cffd-4c80-9904-fa37fffe840e)

In my case, it would be: `s3://constanca-test-esf/config.yaml`, and this bucket looks like this:
![image](https://github.com/elastic/elastic-serverless-forwarder/assets/113898685/6b192530-4679-4e50-b94e-58cb1b9306ac)

The `config.yaml` looks like this:
```yaml
"inputs":
- "id": "arn:aws:logs:eu-north-1:627286350134:log-group:constanca-test-esf:*"
  "outputs":
  - "args":
      "api_key": "..."
      "elasticsearch_url": "https://terraform-8b3bac.es.eu-central-1.aws.cloud.es.io"
      "es_datastream_name": "logs-esf.cloudwatch-default"
    "type": "elasticsearch"
  "type": "cloudwatch-logs"
```

Then I sent an event in my cloudwatch logs group:
![image](https://github.com/elastic/elastic-serverless-forwarder/assets/113898685/02a34bdc-0f6d-4b39-8a6d-0f783e1ffd7e)

And if I look in Discover I can see it there:
![image](https://github.com/elastic/elastic-serverless-forwarder/assets/113898685/246868a5-9446-410c-8550-71db1a1d6a1a)
