### ISSUE TITLE
Unable to deploy the using cloudformation SAR method of deployment ( Tried with > 1.6.0 even with latest )

### ISSUE THREAD

**Issue by umairahmad0** [elastic/elastic-serverless-forwarder#882]
**Description:**

Main stack fails with the following msg 
=>
Embedded stack arn:aws:cloudformation:eu-central-1:1234567890:stack/serverlessrepo-elastic-serverless-forwarder-ElasticServerlessForwarderApplication-BNALYHMJ1J0Q/66afb100-21b6-11f0-9fb5-06f0ca99d249 was not successfully created: Received malformed response from transform 1234567890::elastic-serverless-forwarder-macro

Nested Stack 1 (serverlessrepo-elastic-serverless-forwarder-ElasticServerlessForwarderApplication-BNALYHMJ1J0Q) fails with this error 
=>
Received malformed response from transform 425014014036::elastic-serverless-forwarder-macro

Nested Stack 3 (serverlessrepo-elastic-serverless-forwarder-ElasticServerlessForwarderEventMacro-JNP3J9FB21AR) initiate a delete

**Expected behaviour**

Stack in CREATE_COMPLETE with resources deployed

**Current Behaviour:**

Stack is failing as described in the description of the issue

**Reproducing steps**

The template that I am using 
Tried semantic versions > 1.6.0 and even tried the latest one

**PreRequisite:**
An s3 bucket with the configuration file
A log group that can be provided in the parameters

**To reproduce, deploy it using this command** 
aws cloudformation deploy --template-file template.yaml --stack-name esf-cloudformation-deployment --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND

template.yaml
`
# aws cloudformation deploy --template-file template.yaml --stack-name esf-cloudformation-deployment --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND

Transform: AWS::Serverless-2016-10-31
Resources:
  SarCloudformationDeployment:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: 'arn:aws:serverlessrepo:eu-central-1:267093732750:applications/elastic-serverless-forwarder'
        SemanticVersion: '1.7.0'  ## SET TO CORRECT SEMANTIC VERSION (MUST BE GREATER THAN 1.6.0)
      Parameters:
        ElasticServerlessForwarderS3ConfigFile: "s3://aws-elastic-forwarder-config-425014014036/config.yaml"
        ElasticServerlessForwarderCloudWatchLogsEvents: "/aws/lambda/testForwarderLambada"`

**Comment by zmoog** [comment]
Hey @umairahmad0, thank you for reporting you problem in this GH issue.

I tried to format your template file:

```yaml
Transform: AWS::Serverless-2016-10-31
Resources:
  SarCloudformationDeployment:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: 'arn:aws:serverlessrepo:eu-central-1:267093732750:applications/elastic-serverless-forwarder'
        SemanticVersion: '1.7.0' ## SET TO CORRECT SEMANTIC VERSION (MUST BE GREATER THAN 1.6.0)
      Parameters:
        ElasticServerlessForwarderS3ConfigFile: "s3://aws-elastic-forwarder-config-425014014036/config.yaml"
        ElasticServerlessForwarderCloudWatchLogsEvents: "/aws/lambda/testForwarderLambada"`
```

The `ElasticServerlessForwarderCloudWatchLogsEvents` parameter value must be the ARN of the log group. This is probably causing the "Received malformed response from transform" error.

I suggest the following changes:

- Replace the `ElasticServerlessForwarderCloudWatchLogsEvents` value with the log group ARN. For example, `arn:aws:logs:eu-west-1:267093732750:log-group:mbranca-test:*`. See https://www.elastic.co/docs/reference/aws-forwarder/aws-deploy-elastic-serverless-forwarder#_inputs for more info on the parameters.
- `SemanticVersion`: use the latest ESF version, currently `1.19.0`
